### ISSUE TITLE
configure does not identify Ubuntu if run in WSL2.

### ISSUE THREAD

**Issue by pweigel** [arguelles/nuSQuIDS#31]
Configure was giving me some trouble with finding the python libraries, turns out that `uname -a` will not give you an "ubuntu" if you're running Ubuntu with WSL2 (or WSL1 probably). My quick fix was to add another if to check for WSL in the output of uname. Maybe there's a better way to check the distro?
https://github.com/arguelles/nuSQuIDS/blob/354771d0893abc997178268688cca757d2e79cab/configure#L161

**Comment by cnweaver** [comment]
Unfortunately, there is no single, sure way I'm aware of to check the variant of Linux. Does `lsb_release -si` work and output anything useful within WSL's Ubuntu? (It's my understanding that WSL can install various Linux distros, so I don't think we can assume that it is always Ubuntu, although that is the default it uses.)

**Comment by pweigel** [comment]
Sorry for the late reply: `lsb_release -si` does indeed output "Ubuntu" for both WSL 1 and 2 versions.

**Comment by cnweaver** [comment]
Excellent, that gives us a fighting chance. I should be able to make a patch based on that and some other heuristics to cover this.

**Comment by cnweaver** [comment]
My attempted fix is in as https://github.com/arguelles/nuSQuIDS/commit/6b030a86ab446dcf89c11489d529ed223908e70b ; please let me know if that solves the problem for you.

**Comment by pweigel** [comment]
Yup, seems to work on my system!
