### ISSUE TITLE
Readable example notebook?

### ISSUE THREAD

**Issue by samiur06** [arguelles/nuSQuIDS#38]
Hi there,

The python example notebook (`resources/python/example/nuSQUIDS-DEMO.ipynb`) has a glitch, that's why we can't read it. Is it possible to fix that? 

It is a minor issue, however, it will be convenient to see the code and the results in notebook format. 

Regards,
Samiur

**Comment by cnweaver** [comment]
Sorry this isn't working for you; we'd like to fix that. Could you be specific about what the problem is, at least at the level of what error you get from ipython/jupyter when you try to load the notebook? That could help us get at the problem more quickly.

**Comment by samiur06** [comment]
When I open the notebook in my machine, this error shows up `NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...')`. Note that the  [current github page](https://github.com/arguelles/nuSQuIDS/blob/master/resources/python/example/nuSQUIDS-DEMO.ipynb) is also not responding due to the error.

**Comment by cnweaver** [comment]
I see, yes, the file does appear to be significantly corrupted.
