### ISSUE TITLE
Two-neutrino mode fails

### ISSUE THREAD

**Issue by JCarpioD** [arguelles/nuSQuIDS#9]
While running nuSQUIDS nus(numneu,neutrino) with numneu=2, the file executes and crashes with segmentation fault during EvolveState( ). This error comes from the attempt to evaluate HI, which always constructs the potential assuming three neutrino flavours. This is done even when propagating through the vacuum. This problem was easily fixed with an if statement.

The second problem is an error in MatrixExp.h (constant density mode), where one_normest_core
assigns a parameter 't' the default value t=2. An error is raised because of the statement
if (t >= A->size1)
    throw std::runtime_error("t should be smaller than the order of the matrix.");
where A is an nxn matrix. For n = 2 this will give an error. This was fixed by changing the default value of 't' to 1, although I don't know if this will cause any trouble when doing the exponentials.

**Comment by arguelles** [comment]
The code has being design for full three neutrino calculations and has been optimized accordingly. Modifying to two neutrinos will require extensive changes and not provide new features.
